{% set name = "jupyterlab-transient-display-data" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/transient-display-data/transient_display_data-{{ version }}.tar.gz
  sha256: cb9dc673c66cb5ef6d79039e0e261cea3737a06a9e918d5781e1be85d7075f7f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - nodejs
  host:
    - hatch-jupyter-builder
    - hatch-nodejs-version
    - hatchling
    - jupyter-packaging
    - pip
    - python {{ python_min }}
  run:
    - jupyterlab >=3.0.0
    - nodejs
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - jupyter labextension list
    - jupyter lab build
    - jupyter labextension list 1>labextensions 2>&1  # [unix]
    - grep "transient-display-data.*enabled.*OK" labextensions  # [unix]


about:
  home: https://github.com/vatlab/transient-display-data
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A JupyterLab extension for the rendering transient-display-data messages
  dev_url: https://github.com/vatlab/transient-display-data

extra:
  recipe-maintainers:
    - BoPeng
    - izahn
